In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype

dtype('int32')

In [7]:
a.itemsize

4

In [8]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([6, 7, 8])

In [12]:
b 

array([6, 7, 8])

In [13]:
type(b)

numpy.ndarray

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((2,3,4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
np.empty((2,3))

array([[1.01582801e+094, 3.54586565e+068, 1.57001898e+155],
       [3.71754479e+177, 3.97949006e-315, 0.00000000e+000]])

In [17]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [18]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [19]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [20]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [21]:
b

array([0, 1, 2, 3])

In [22]:
print(id(b))

1606765660000
